update, got build.prop error
Change-Id: Ia68064c188dd06ad400491bdbd24dff0448c26f3

diff --git a/releasetools/squisher b/releasetools/squisher
--- a/releasetools/squisher
+++ b/releasetools/squisher
@@ -1,8 +1,11 @@
 #!/bin/sh
 #
-# Squish a otapackage for distribution
+# Squish a CM otapackage for distribution
 # cyanogen
 #
+
+echo "spyder SQUISHER:"
+echo "================"
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -24,21 +27,50 @@ if [ -z "$OUT" -o ! -d "$OUT" ]; then
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
-    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
+    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
 elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
 else
-    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
+    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-	echo "$OTAPACKAGE doesn't exist!";
+	echo "$OTAPACKAGE doesn't exist!"
 	exit 1
 fi
 
-OPTICHARGER=$ANDROID_BUILD_TOP/device/motorola/spyder/releasetools/opticharger
+OPTICHARGER=$ANDROID_BUILD_TOP/vendor/cyanogen/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
+
+# Some products want a squashfs for xbin for space
+case "$TARGET_PRODUCT" in
+	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+	*) WANT_SQUASHFS=0 ;;
+esac
+
+if [ "$WANT_SQUASHFS" -eq 1 ]; then
+	fatal=0
+	MKSQUASHFS_VER_REQ=4
+	if type mksquashfs >/dev/null 2>&1; then
+		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+			echo
+			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+			fatal=1
+		fi
+	else
+		echo
+		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+		fatal=1
+	fi
+
+	if [ "$fatal" -ne 0 ]; then
+		echo
+		echo "       Unoptimized package is still available at"
+		echo "         $OTAPACKAGE"
+		exit $fatal
+	fi
+fi
 
 REPACK=$OUT/repack.d
 printf "Sanitizing environment..."
@@ -59,12 +91,6 @@ $OPTICHARGER framework-res.apk
 cd $REPACK/ota/system/app
 find ./ -name \*.apk | $XARGS $OPTICHARGER
 )
-
-# Remove unwanted Apps
-rm $REPACK/ota/system/app/FmRxApp.apk
-rm $REPACK/ota/system/app/FmService.apk
-rm $REPACK/ota/system/app/FmTxApp.apk
-rm $REPACK/ota/system/app/RomManager.apk
 
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
@@ -102,6 +128,10 @@ $SED -i \
 	-e '/ro\.build\.type/s/eng/user/' \
 	$REPACK/ota/system/build.prop
 
+# Include device specific script
+if [ -f $ANDROID_BUILD_TOP/device/motorola/spyder/releasetools/squisher.sh ]; then
+	. $ANDROID_BUILD_TOP/device/motorola/spyder/releasetools/squisher.sh
+fi
 
 # Delete unnecessary binaries
 ( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
@@ -113,16 +143,24 @@ $SED -i \
 rm -rf $REPACK/ota/recovery
 
 # Strip modules
-[ -d $REPACK/ota/system/lib/modules ] && \
-	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
-
-# Copy libvoicesearch as it's getting messed up in the build
-cp -f $ANDROID_BUILD_TOP/device/motorola/spyder/prebuilt/lib/libvoicesearch.so $REPACK/ota/system/lib/libvoicesearch.so
+find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
 # Determine what to name the new signed package
-REALDATE=`date +%F-%H_%M`
-
-OUTFILE=$OUT/ICS-4.0.3_r1-$TARGET_PRODUCT-$REALDATE.zip
+if [ -z "$CYANOGEN_NIGHTLY" ]; then
+	MODVERSION=`sed -n -e'/ro\.modversion/s/^.*CyanogenMod-//p' $REPACK/ota/system/build.prop`
+	: ${MODVERSION:=nightly}
+	OUTFILE=$OUT/update-cm-$MODVERSION-signed.zip
+else
+	OUTFILE=$OUT/update-squished.zip
+#	if [ "$TARGET_PRODUCT" = "cyanogen_spyder" ]; then
+#		MODVERSION=`sed -n -e'/ro\.modversion/s/^.*CyanogenMod-//p' $REPACK/ota/system/build.prop`
+#		OUTFILE=$OUT/cm$MODVERSION.zip
+#		if [ -n "$CYANOGEN_NIGHTLY_BOOT" ]; then
+#			MODVERSION=`echo $MODVERSION | sed -r 's/NIGHTLY/BOOT'$CYANOGEN_NIGHTLY_BOOT'/'`
+#			OUTFILE=$OUT/cm$MODVERSION.zip
+#		fi
+#	fi
+fi
 
 # Pack it up and sign
 printf "Zipping package..."
@@ -130,7 +168,7 @@ printf "Zipping package..."
 echo
 printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
-java -Xmx1536m \
+java -Xmx1024m \
 	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
 	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
 	$REPACK/update.zip $OUTFILE
@@ -148,14 +186,10 @@ echo
 echo "Package complete: $OUTFILE"
 cat $img.md5sum
 echo
+# Build date and current time:
+cat $OUT/system/build.prop | grep ro.build.date=
+date "+%Y%m%d-%H%M"
+echo
 )
-
-#if you want to run a custom upload script put it in ~/upload.sh
-if [ -f ~/razr175.sh ];
-then
-	echo "Running upload script"
-	upload=~/razr175.sh
-	. $upload
-fi
 
 exit 0
